# Generated by Django 3.0.8 on 2020-07-21 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt_app', '0003_auto_20200722_0012'),
        ('acc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userInfo', to='mgmt_app.College'),
        ),
    ]
