# Generated by Django 3.0.8 on 2020-07-21 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=64)),
                ('university', models.CharField(choices=[('1', 'University of Information Technology and Communications')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=64)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgmt_app.College')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='students_pics')),
                ('first_name', models.CharField(max_length=16)),
                ('second_name', models.CharField(max_length=16)),
                ('third_name', models.CharField(max_length=16)),
                ('fourth_name', models.CharField(max_length=16)),
                ('sur_name', models.CharField(max_length=16)),
                ('mother_full_name', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=7)),
                ('birthdate', models.DateTimeField()),
                ('verified_personal_info', models.BooleanField(default=False)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('parent_phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('first_address', models.CharField(blank=True, max_length=64)),
                ('second_address', models.CharField(blank=True, max_length=64)),
                ('verified_contact_info', models.BooleanField(default=False)),
                ('nationality', models.CharField(max_length=16)),
                ('birth_city', models.CharField(blank=True, choices=[('Anbar', 'Anbar'), ('Babil', 'Babil'), ('Baghdad', 'Baghdad'), ('Basra', 'Basra'), ('Dhi Qar', 'Dhi Qar'), ('Al-Qādisiyyah', 'Al-Qādisiyyah'), ('Diyala', 'Diyala'), ('Duhok', 'Duhok'), ('Erbil', 'Erbil'), ('Karbala', 'Karbala'), ('Kirkuk', 'Kirkuk'), ('Maysan', 'Maysan'), ('Muthanna', 'Muthanna'), ('Najaf', 'Najaf'), ('Nineveh', 'Nineveh'), ('Saladin', 'Saladin'), ('Sulaymaniyah', 'Sulaymaniyah'), ('Wasit', 'Wasit')], max_length=16)),
                ('living_city', models.CharField(blank=True, choices=[('Anbar', 'Anbar'), ('Babil', 'Babil'), ('Baghdad', 'Baghdad'), ('Basra', 'Basra'), ('Dhi Qar', 'Dhi Qar'), ('Al-Qādisiyyah', 'Al-Qādisiyyah'), ('Diyala', 'Diyala'), ('Duhok', 'Duhok'), ('Erbil', 'Erbil'), ('Karbala', 'Karbala'), ('Kirkuk', 'Kirkuk'), ('Maysan', 'Maysan'), ('Muthanna', 'Muthanna'), ('Najaf', 'Najaf'), ('Nineveh', 'Nineveh'), ('Saladin', 'Saladin'), ('Sulaymaniyah', 'Sulaymaniyah'), ('Wasit', 'Wasit')], max_length=16)),
                ('national_id', models.CharField(blank=True, max_length=16)),
                ('national_id_issue_place', models.CharField(blank=True, choices=[('Anbar', 'Anbar'), ('Babil', 'Babil'), ('Baghdad', 'Baghdad'), ('Basra', 'Basra'), ('Dhi Qar', 'Dhi Qar'), ('Al-Qādisiyyah', 'Al-Qādisiyyah'), ('Diyala', 'Diyala'), ('Duhok', 'Duhok'), ('Erbil', 'Erbil'), ('Karbala', 'Karbala'), ('Kirkuk', 'Kirkuk'), ('Maysan', 'Maysan'), ('Muthanna', 'Muthanna'), ('Najaf', 'Najaf'), ('Nineveh', 'Nineveh'), ('Saladin', 'Saladin'), ('Sulaymaniyah', 'Sulaymaniyah'), ('Wasit', 'Wasit')], max_length=24)),
                ('passport_id', models.CharField(blank=True, max_length=24)),
                ('passport_issue_place', models.CharField(blank=True, choices=[('Anbar', 'Anbar'), ('Babil', 'Babil'), ('Baghdad', 'Baghdad'), ('Basra', 'Basra'), ('Dhi Qar', 'Dhi Qar'), ('Al-Qādisiyyah', 'Al-Qādisiyyah'), ('Diyala', 'Diyala'), ('Duhok', 'Duhok'), ('Erbil', 'Erbil'), ('Karbala', 'Karbala'), ('Kirkuk', 'Kirkuk'), ('Maysan', 'Maysan'), ('Muthanna', 'Muthanna'), ('Najaf', 'Najaf'), ('Nineveh', 'Nineveh'), ('Saladin', 'Saladin'), ('Sulaymaniyah', 'Sulaymaniyah'), ('Wasit', 'Wasit')], max_length=16)),
                ('passport_expire_date', models.DateTimeField(blank=True, null=True)),
                ('verified_nation_info', models.BooleanField(default=False)),
                ('medical_status', models.CharField(blank=True, max_length=128)),
                ('school_document', models.FileField(blank=True, upload_to='school_docs')),
                ('degree_approval', models.FileField(blank=True, upload_to='school_docs')),
                ('average', models.IntegerField()),
                ('verified_school_info', models.BooleanField(default=False)),
                ('stage', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2)),
                ('group', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2)),
                ('enroll_date', models.DateTimeField(blank=True, null=True)),
                ('examination_id', models.CharField(blank=True, max_length=24)),
                ('status', models.CharField(blank=True, choices=[('Pass_1', 'Pass / first attepmt'), ('Pass_2', 'Pass / second attempt'), ('Fail', 'Fail'), ('Upload_1', 'Upload 1'), ('Upload_2', 'Upload 2')], max_length=64)),
                ('verified_college_info', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mgmt_app.College')),
                ('department', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mgmt_app.Department')),
            ],
        ),
    ]
