# Generated by Django 3.0.8 on 2020-07-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college',
            field=models.CharField(choices=[('BIC', 'Business Informatics College'), ('EC', 'College of Engineering'), ('MC', 'Medical College')], default=' ', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='college',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
