# Generated by Django 3.0.8 on 2020-07-21 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt_app', '0002_auto_20200722_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='college',
        ),
        migrations.AlterField(
            model_name='college',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='college',
            name='title',
            field=models.CharField(choices=[('BIC', 'Business Informatics College'), ('EC', 'College of Engineering'), ('MC', 'Medical College')], max_length=128),
        ),
        migrations.AlterField(
            model_name='department',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='mgmt_app.College'),
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='mgmt_app.College'),
        ),
    ]
