# Generated by Django 3.0.8 on 2020-07-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt_app', '0004_auto_20200725_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='final_grade',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
